data:
  data: BeamDI02
  subset: BeamDI02_T8000
  validset: BeamDI02_V1000
loss:
  evaluations:
  - - R2
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - epsilon: 1.0e-08
      reduction: mean
  - - MAE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: mean
  losses:
  - - LpLoss
    - 1
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - d: 2
      p: 2
      reduction: true
      size_average: true
model:
  model: ResNet
  para:
    embed_dim: 128
    in_channels: 4
    out_channels: 1
paths:
  config_path: ./configs\EXP1-ResNet-BeamDI02_T8000-DD-250721-170607.yaml
  results_path: ./results\ResNet-BeamDI02\EXP1-ResNet-BeamDI02_T8000-DD-250721-170607
project:
  case: EXP1-ResNet-BeamDI02_T8000-DD-250721-170607
  description: BeamDI02_V1000
  project: ResNet-BeamDI02
  tasktype: DD
randomseed: 114514
scheduler:
  decay_rate: 0.9798
  initial_ratio: 0
  scheduler: ExpLRScheduler
  warmup_epochs: 20
status:
  train_count: 1
  train_history:
  - end_time: '2025-07-21 18:22:53'
    start_time: '2025-07-21 17:39:33'
train:
  batch_size: 16
  epochs: 150
  in_channels: 3
  learning_rate: 0.001
  out_channels: 1
  weight_decay: 0.01
