data:
  data: BeamDI02
  subset: BeamDI02_T8000
  validset: BeamDI02_V1000
loss:
  evaluations:
  - - R2
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - epsilon: 1.0e-08
      reduction: mean
  - - MAE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: mean
  - - SCLoss
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - device: cuda
      grid_len: 540
      model_path: .\results\MSFNO-BeamDI02\EXP1-MSFNO-BeamDI02_T8000-DD-250721-164537\model\MSFNO-250721170758.pt
  losses:
  - - LpLoss
    - 1
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - d: 2
      p: 2
      reduction: true
      size_average: true
model:
  model: MBCNNSR
  para:
    dim1: 16
    dim2fct: 2
    inlen: 9
    num_subnets: 3
    outlen: 540
paths:
  config_path: ./configs\EXP4-MBCNNSR-BeamDI02_T8000-RD-250724-185445.yaml
  results_path: ./results\MBCNNSR-BeamDI02\EXP4-MBCNNSR-BeamDI02_T8000-RD-250724-185445
project:
  case: EXP4-MBCNNSR-BeamDI02_T8000-RD-250724-185445
  description: 250714 MBCNNSR
  project: MBCNNSR-BeamDI02
  tasktype: RD
randomseed: 114514
scheduler:
  decay_rate: 0.9798
  initial_ratio: 1.0e-05
  scheduler: ExpLRScheduler
  warmup_epochs: 20
status:
  train_count: 1
  train_history:
  - end_time: '2025-07-24 20:18:51'
    start_time: '2025-07-24 19:58:06'
train:
  batch_size: 16
  down_idx:
  - 0
  - 68
  - 135
  - 203
  - 270
  - 337
  - 405
  - 473
  - 540
  epochs: 150
  gt_idx: 540
  in_channels: 3
  learning_rate: 0.001
  uncertainty_lr: 0.001
  weight_decay: 0.01
