data:
  data: beamdi_num
  subset: beamdi_num_t8000
  validset: beamdi_num_v1000
loss:
  evaluations:
  - - R2
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: true
      size_average: true
  - - MAE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: true
      size_average: true
  - - MAPE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: true
      size_average: true
  losses:
  - - LpLoss
    - 1
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - d: 2
      p: 2
      reduction: true
      size_average: true
model:
  model: mosrnet
  para:
    dim1: 16
    dim2fct: 2
    inlen: 9
    num_subnets: 3
    outlen: 540
paths:
  config_path: ./configs\mosrnet-beamdi_num_t8000-run01-250813-194758.yaml
  results_path: ./results\mosrnet-beamdi_num\mosrnet-beamdi_num_t8000-run01-250813-194758
project:
  case: mosrnet-beamdi_num_t8000-run01-250813-194758
  description: 'SHM Framework of MoSRNet and MS-FNO '
  project: mosrnet-beamdi_num
randomseed: 114514
scheduler:
  decay_rate: 0.9798
  initial_ratio: 1.0e-05
  scheduler: ExpLRScheduler
  warmup_epochs: 20
status:
  train_count: 17
  train_history:
  - end_time: null
    start_time: '2025-08-13 20:09:27'
  - end_time: null
    start_time: '2025-08-13 20:11:04'
  - end_time: null
    start_time: '2025-08-13 20:13:35'
  - end_time: null
    start_time: '2025-08-13 20:14:35'
  - end_time: null
    start_time: '2025-08-13 20:19:38'
  - end_time: null
    start_time: '2025-08-13 20:20:15'
  - end_time: null
    start_time: '2025-08-13 20:20:52'
  - end_time: null
    start_time: '2025-08-13 20:22:58'
  - end_time: null
    start_time: '2025-08-13 20:24:04'
  - end_time: null
    start_time: '2025-08-13 20:30:59'
  - end_time: null
    start_time: '2025-08-13 20:39:54'
  - end_time: null
    start_time: '2025-08-13 20:40:35'
  - end_time: null
    start_time: '2025-08-13 20:41:08'
  - end_time: null
    start_time: '2025-08-13 20:56:07'
  - end_time: null
    start_time: '2025-08-13 20:57:19'
  - end_time: '2025-08-13 20:58:23'
    start_time: '2025-08-13 20:58:12'
  - end_time: '2025-08-13 21:26:25'
    start_time: '2025-08-13 21:26:15'
train:
  batch_size: 16
  down_idx:
  - 0
  - 68
  - 135
  - 203
  - 270
  - 337
  - 405
  - 473
  - 540
  epochs: 2
  gt_idx: 540
  in_channels: 3
  learning_rate: 0.001
  weight_decay: 0.01
