data:
  data: beamdi_num
  subset: beamdi_num_t8000
  validset: beamdi_num_v1000
loss:
  evaluations:
  - - R2
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: true
      size_average: true
  - - MAE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: true
      size_average: true
  - - MAPE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: true
      size_average: true
  losses:
  - - LpLoss
    - 1
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - d: 2
      p: 2
      reduction: true
      size_average: true
model:
  model: mosrnet
  para:
    dim1: 16
    dim2fct: 2
    inlen: 9
    num_subnets: 3
    outlen: 541
paths:
  config_path: ./configs\mosrnet-beamdi_num_t8000-run01-250814-164957.yaml
  results_path: ./results/models\mosrnet-beamdi_num\mosrnet-beamdi_num_t8000-run01-250814-164957
project:
  case: mosrnet-beamdi_num_t8000-run01-250814-164957
  description: 'SHM Framework of MoSRNet and MS-FNO '
  project: mosrnet-beamdi_num
randomseed: 114514
scheduler:
  decay_rate: 0.97
  initial_ratio: 1.0e-05
  scheduler: ExpLRScheduler
  warmup_epochs: 20
status:
  train_count: 5
  train_history:
  - end_time: '2025-08-14 17:12:05'
    start_time: '2025-08-14 16:59:52'
  - end_time: null
    start_time: '2025-08-22 14:07:57'
  - end_time: null
    start_time: '2025-08-22 14:10:34'
  - end_time: null
    start_time: '2025-08-22 14:11:03'
  - end_time: '2025-08-22 14:26:17'
    start_time: '2025-08-22 14:12:44'
train:
  batch_size: 16
  down_idx:
  - 0
  - 68
  - 135
  - 203
  - 270
  - 337
  - 405
  - 473
  - 540
  epochs: 120
  gt_idx: 541
  in_channels: 3
  learning_rate: 0.001
  weight_decay: 0.01
