data:
  data: beamdi_num
  subset: beamdi_num_t8000
  validset: beamdi_num_v1000
loss:
  evaluations:
  - - R2
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - epsilon: 1.0e-08
      reduction: mean
  - - MAE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: mean
  losses:
  - - LpLoss
    - 1
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - d: 2
      p: 2
      reduction: true
      size_average: true
model:
  model: msfno
  para:
    embed_dim: 128
    fno_layers: 3
    fno_modes: 16
    in_channels: 4
    mode_length: 541
    out_channels: 1
paths:
  config_path: ./configs\msfno-beamdi_num_t8000-run01-250814-145703.yaml
  results_path: ./results\msfno-beamdi_num\msfno-beamdi_num_t8000-run01-250814-145703
project:
  case: msfno-beamdi_num_t8000-run01-250814-145703
  description: SHM Framework of MoSRNet and MS-FNO
  project: msfno-beamdi_num
randomseed: 114514
scheduler:
  decay_rate: 0.97
  initial_ratio: 0
  scheduler: ExpLRScheduler
  warmup_epochs: 20
train:
  batch_size: 16
  epochs: 120
  in_channels: 3
  learning_rate: 0.001
  out_channels: 1
  weight_decay: 0.01
