data:
  data: beamdi_num
  subset: beamdi_num_t8000
  validset: beamdi_num_v1000
loss:
  evaluations:
  - - R2
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: true
      size_average: true
  - - MAE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: true
      size_average: true
  - - MAPE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: true
      size_average: true
  losses:
  - - LpLoss
    - 1
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - d: 2
      p: 2
      reduction: true
      size_average: true
model:
  model: msfno
  para:
    embed_dim: 128
    fno_layers: 3
    fno_modes: 16
    in_channels: 4
    mode_length: 541
    out_channels: 1
paths:
  config_path: ./configs\msfno-beamdi_num_t8000-run01-250814-165002.yaml
  results_path: ./results\msfno-beamdi_num\msfno-beamdi_num_t8000-run01-250814-165002
project:
  case: msfno-beamdi_num_t8000-run01-250814-165002
  description: SHM Framework of MoSRNet and MS-FNO
  project: msfno-beamdi_num
randomseed: 114514
scheduler:
  decay_rate: 0.975
  initial_ratio: 0
  scheduler: ExpLRScheduler
  warmup_epochs: 20
status:
  train_count: 1
  train_history:
  - end_time: '2025-08-14 17:45:37'
    start_time: '2025-08-14 17:12:06'
train:
  batch_size: 16
  epochs: 170
  in_channels: 3
  learning_rate: 0.001
  out_channels: 1
  weight_decay: 0.01
