data:
  data: beamdi_num
  subset: beamdi_num_t8000
  validset: beamdi_num_v1000
loss:
  evaluations:
  - - R2
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - epsilon: 1.0e-08
      reduction: mean
  - - MAE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: mean
  losses:
  - - LpLoss
    - 1
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - d: 2
      p: 2
      reduction: true
      size_average: true
model:
  model: msfno
  para:
    embed_dim: 128
    fno_layers: 3
    fno_modes: 16
    in_channels: 4
    mode_length: 541
    out_channels: 1
paths:
  config_path: ./configs\msfno-beamdi_num_t8000-run01-250813-194908.yaml
  results_path: ./results\msfno-beamdi_num\msfno-beamdi_num_t8000-run01-250813-194908
project:
  case: msfno-beamdi_num_t8000-run01-250813-194908
  description: SHM Framework of MoSRNet and MS-FNO
  project: msfno-beamdi_num
randomseed: 114514
scheduler:
  decay_rate: 0.9798
  initial_ratio: 0
  scheduler: ExpLRScheduler
  warmup_epochs: 20
status:
  train_count: 11
  train_history:
  - end_time: null
    start_time: '2025-08-13 21:03:24'
  - end_time: null
    start_time: '2025-08-13 21:06:17'
  - end_time: null
    start_time: '2025-08-13 21:07:40'
  - end_time: null
    start_time: '2025-08-13 21:09:10'
  - end_time: null
    start_time: '2025-08-13 21:10:41'
  - end_time: null
    start_time: '2025-08-13 21:13:05'
  - end_time: null
    start_time: '2025-08-13 21:14:15'
  - end_time: null
    start_time: '2025-08-13 21:15:51'
  - end_time: '2025-08-13 21:19:19'
    start_time: '2025-08-13 21:18:58'
  - end_time: '2025-08-13 21:24:22'
    start_time: '2025-08-13 21:24:01'
  - end_time: '2025-08-13 21:25:03'
    start_time: '2025-08-13 21:24:42'
train:
  batch_size: 16
  epochs: 2
  in_channels: 3
  learning_rate: 0.001
  out_channels: 1
  weight_decay: 0.01
