data:
  data: beamdi_num
  subset: beamdi_num_t8000
  validset: beamdi_num_v1000
loss:
  evaluations:
  - - R2
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - epsilon: 1.0e-08
      reduction: mean
  - - MAE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: mean
  losses:
  - - LpLoss
    - 1
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - d: 2
      p: 2
      reduction: true
      size_average: true
model:
  model: resnet
  para:
    embed_dim: 128
    in_channels: 4
    out_channels: 1
paths:
  config_path: ./configs\resnet-beamdi_num_t8000-run01-250813-194922.yaml
  results_path: ./results\resnet-beamdi_num\resnet-beamdi_num_t8000-run01-250813-194922
project:
  case: resnet-beamdi_num_t8000-run01-250813-194922
  description: SHM Framework of MoSRNet and MS-FNO
  project: resnet-beamdi_num
randomseed: 114514
scheduler:
  decay_rate: 0.9798
  initial_ratio: 0
  scheduler: ExpLRScheduler
  warmup_epochs: 20
status:
  train_count: 2
  train_history:
  - end_time: null
    start_time: '2025-08-13 21:28:43'
  - end_time: '2025-08-13 21:31:13'
    start_time: '2025-08-13 21:30:22'
train:
  batch_size: 16
  epochs: 2
  in_channels: 3
  learning_rate: 0.001
  out_channels: 1
  weight_decay: 0.01
