data:
  data: beamdi_num
  subset: beamdi_num_t8000
  validset: beamdi_num_v1000
loss:
  evaluations:
  - - R2
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: true
      size_average: true
  - - MAE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: true
      size_average: true
  - - MAPE
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - reduction: true
      size_average: true
  losses:
  - - LpLoss
    - 1
    - - 1
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
    - d: 2
      p: 2
      reduction: true
      size_average: true
model:
  model: resnet
  para:
    embed_dim: 128
    in_channels: 4
    out_channels: 1
paths:
  config_path: ./configs\resnet-beamdi_num_t8000-run01-250814-165006.yaml
  results_path: ./results/models\resnet-beamdi_num\resnet-beamdi_num_t8000-run01-250814-165006
project:
  case: resnet-beamdi_num_t8000-run01-250814-165006
  description: SHM Framework of MoSRNet and MS-FNO
  project: resnet-beamdi_num
randomseed: 114514
scheduler:
  decay_rate: 0.975
  initial_ratio: 0
  scheduler: ExpLRScheduler
  warmup_epochs: 20
status:
  train_count: 2
  train_history:
  - end_time: '2025-08-14 19:04:50'
    start_time: '2025-08-14 17:45:38'
  - end_time: '2025-08-22 15:37:39'
    start_time: '2025-08-22 14:47:39'
train:
  batch_size: 16
  epochs: 170
  in_channels: 3
  learning_rate: 0.001
  out_channels: 1
  weight_decay: 0.01
